routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => ['web', 'checkuserlevel:1']], function() {
Route::group(['middleware' => 'auth'], function() {
    Route::resource('classroom', 'ClassroomController');
	Route::resource('teacher', 'TeacherController');
	Route::resource('student', 'StudentController');
	Route::post('reportshow', 'ReportController@showlist')->name('reportshow');
	Route::resource('report', 'ReportController');
	Route::post('makePDF', 'ReportController@makePDF')->name('makePDF');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
    protected $table = 'class';
    protected $primaryKey = 'class_id';

    public function teacher()
    {
    	return $this->belongsTo('App\Teacher', 'foreign_key');
    }

    public function student()
    {
    	return $this->hasMany('App\Student', 'student_id');
    }
}

app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Classroom;
use App\Teacher;
use App\Student;
use Redirect;
use PDF;

class ClassroomController extends Controller
{
    protected $message = array(
        'name.required' => 'Fill name of Classroom',
        'teacher.required' => 'Please choose a teacher',

    );

    protected $rules = array(
        'name' => 'required|unique:class',
        // 'teacher' => 'required',

    );

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $classroom = Classroom::all();
        $teacher = Teacher::all();

        return view('classroom.index', compact('classroom', 'teacher'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teacher = Teacher::all();
        $student = Student::all();

        return view('classroom.create', compact('teacher', 'student'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->rules, $this->message);

        $classroom = new Classroom;
        $classroom->name = $request['name'];
        // $classroom->teacher_id = $request['teacher'];
        $classroom->save();

        return Redirect::route('classroom.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = Teacher::all();
        $student = Student::all();
        $classroom = Classroom::find($id);

        return view('classroom.edit', compact('classroom', 'teacher', 'student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->rules, $this->message);

        $classroom = Classroom::find($id);
        $classroom->name = $request['name'];
        $classroom->teacher_id = $request['teacher'];
        $classroom->update();

        return Redirect::route('classroom.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $classroom = Classroom::find($id);
        $classroom->delete();

        return Redirect::route('classroom.index');
    }

    public function makePDF(Request $request)
    {
        $teacher = DB::select('select * from teacher where class_id = :class_id', ['class_id' => $request['classroom']]);
        $student = DB::select('select * from student where class_id = :class_id', ['class_id' => $request['classroom']]);
        $class = Classroom::all();

        $pdf = PDF::loadView('report.index', compact('teacher', 'student', 'class'));
        $pdf->setPaper('a4', 'potrait');

        return $pdf->stream();
    }
}

resources/views/classroom/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Add Classroom<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('classroom.store') }}">
						{{ csrf_field() }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Classroom</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" value="{{ (old('name')?old('name'):'') }}" autofocus>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('classroom') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/classroom/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Edit Classroom<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('classroom.update', $classroom->class_id) }}">
						{{ csrf_field() }}
						{{ method_field('PATCH') }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Classroom</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" value="{{ $classroom->name }}" autofocus>
							</div>
						</div>

						<!-- <div class="form-group">
							<label for="teacher" class="col-md-3 control-label">Teacher</label>
							<div class="col-md-6">
								<select id="teacher" class="form-control" name="teacher">
									<option value=""> -- Choose Teacher -- </option>
									@foreach($teacher as $teacher)
									    <option value="{{ $teacher->teacher_id }}" {{ $classroom->teacher_id == $teacher->teacher_id ? 'selected' : '' }}>{{ $teacher->name }}</option>
									@endforeach
								</select>
							</div>
						</div> -->

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('classroom') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/classroom/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>List of Classroom
						<a href="{{ route('classroom.create') }}" class="btn btn-success pull-right">Insert</a><br></h4>
				</div>

				<div class="panel-body">
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>Class name</th>
								<!-- <th>Teacher</th> -->
								<!-- <th>Student</th> -->
								<th>Action</th>
							</tr>
						</thead>

						<tbody>
							@foreach ($classroom as $class)
							<tr>
								<td>{{ $class->class_id }}</td>
								<td>{{ $class->name }}</td>
								<!-- <td>
									@foreach($teacher as $guru)
									    {{ $guru->teacher_id == $class->teacher_id ? $guru->name : '' }}
									@endforeach
								</td> -->
								<!-- <td>{{ $class->student_id }}</td> -->
								<td>
									<form method="POST" action="{{ route('classroom.destroy', $class->class_id) }}">
										{{ csrf_field() }}
										{{ method_field('DELETE') }}
										<a href="{{ route('classroom.edit', $class->class_id) }}" class="btn btn-primary">Edit</a>
										<button type="submit" class="btn btn-danger">Delete</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/classroom/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Classroom List</title>
	<link rel="stylesheet" type="text/css" href="{{ asset('public/bootstrap/css/bootstrap.min.css') }}">
</head>
<body>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 align="center">Classroom List</h3>
		</div>

		<div class="panel-body">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>No</th>
						<th>Classname</th>
						<th>Teacher Name</th>
						<th>Student</th>
					</tr>
				</thead>

				<tbody>
					@foreach ($classroom as $data)
					<tr>
						<td>{{ ++$number }}</td>
						<td>{{ $data->classname }}</td>
						<td>{{ $data->teachername }}</td>
						<td>{{ $data->studentname }}</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>