routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => ['web', 'checkuserlevel:1']], function() {
Route::group(['middleware' => 'auth'], function() {
    Route::resource('classroom', 'ClassroomController');
	Route::resource('teacher', 'TeacherController');
	Route::resource('student', 'StudentController');
	Route::post('reportshow', 'ReportController@showlist')->name('reportshow');
	Route::resource('report', 'ReportController');
	Route::post('makePDF', 'ReportController@makePDF')->name('makePDF');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = 'student';
    protected $primaryKey = 'student_id';

    public function class()
    {
    	return $this->belongsTo('App\Class', 'class_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;
use App\Teacher;
use App\Classroom;
use Redirect;

class StudentController extends Controller
{
    protected $message = array(
        'name.required' => 'Fill name of Student',
    );

    protected $rules = array(
        'name' => 'required|unique:student',
    );

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $student = Student::all();

        return view('student.index', compact('student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $student = Student::all();

        return view('student.create', compact('student'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->rules, $this->message);

        $student = new Student;
        $student->name = $request['name'];
        $student->save();

        return Redirect::route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        $classroom = Classroom::all();

        return view('student.edit', compact('student', 'classroom'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, $this->rules, $this->message);

        $student = Student::find($id);
        $student->name = $request['name'];
        $student->class_id = $request['class'];
        $student->update();

        return Redirect::route('student.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);
        $student->delete();

        return Redirect::route('student.index');
    }
}

resources/views/student/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Add Student<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('student.store') }}">
						{{ csrf_field() }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Student</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" autofocus>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('student') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Edit Student<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('student.update', $student->student_id) }}">
						{{ csrf_field() }}
						{{ method_field('PATCH') }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Student</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" value="{{ $student->name }}" autofocus>
							</div>
						</div>

						<div class="form-group">
							<label for="class" class="col-md-3 control-label">Classroom</label>
							<div class="col-md-6">
								<select id="class" class="form-control" name="class">
									<option value=""> -- Choose Classroom -- </option>
									@foreach($classroom as $classroom)
									    <option value="{{ $classroom->class_id }}" {{ $classroom->class_id == $student->class_id ? 'selected' : '' }}>{{ $classroom->name }}</option>
									@endforeach
								</select>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('student') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>List of Student
						<a href="{{ route('student.create') }}" class="btn btn-success pull-right">Insert</a><br></h4>
				</div>

				<div class="panel-body">
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>Student name</th>
								<th>Action</th>
							</tr>
						</thead>

						<tbody>
							@foreach ($student as $student)
							<tr>
								<td>{{ $student->student_id }}</td>
								<td>{{ $student->name }}</td>
								<td>
									<form method="POST" action="{{ route('student.destroy', $student->student_id) }}">
										{{ csrf_field() }}
										{{ method_field('DELETE') }}
										<a href="{{ route('student.edit', $student->student_id) }}" class="btn btn-primary">Edit</a>
										<button type="submit" class="btn btn-danger">Delete</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection