routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => ['web', 'checkuserlevel:1']], function() {
Route::group(['middleware' => 'auth'], function() {
    Route::resource('classroom', 'ClassroomController');
	Route::resource('teacher', 'TeacherController');
	Route::resource('student', 'StudentController');
	Route::post('reportshow', 'ReportController@showlist')->name('reportshow');
	Route::resource('report', 'ReportController');
	Route::post('makePDF', 'ReportController@makePDF')->name('makePDF');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
	protected $table = 'teacher';
	protected $primaryKey = 'teacher_id';

    public function class()
    {
    	return $this->hasMany('App\Class', 'class_id');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Teacher;
use App\Classroom;
use Redirect;
use Closure;

class TeacherController extends Controller
{
    protected $message = array(
        'name.required' => 'Fill name of Teacher',
    );

    protected $rules = array(
        'name' => 'required|unique:teacher',
        'class_id' => 'unique:class',
    );

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teacher = Teacher::all();
        $classroom = Classroom::all();

        return view('teacher.index', compact('teacher', 'classroom'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teacher = Teacher::all();
        $classroom = Classroom::all();

        return view('teacher.create', compact('teacher', 'classroom'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->rules, $this->message);

        $teacher = new Teacher;
        $teacher->name = $request['name'];
        $teacher->class_id = $request['classroom'];
        $teacher->save();

        return Redirect::route('teacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = Teacher::find($id);
        $classroom = Classroom::all();

        return view('teacher.edit', compact('teacher', 'classroom'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, $this->rules, $this->message);

        $teacher = Teacher::find($id);
        $teacher->name = $request['name'];
        $teacher->class_id = $request['class_id'];
        $teacher->update();

        return Redirect::route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teacher = Teacher::find($id);
        $teacher->delete();

        return Redirect::route('teacher.index');
    }
}

resources/views/teacher/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Add Teacher<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('teacher.store') }}">
						{{ csrf_field() }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Teacher</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" autofocus>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('teacher') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/teacher/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>Edit Teacher<br></h4>
				</div>

				<div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{ route('teacher.update', $teacher->teacher_id) }}">
						{{ csrf_field() }}
						{{ method_field('PATCH') }}

						@if ($errors->any())
						    <div class="alert alert-danger"><ul>
						    	@foreach ($errors->all() as $error)
						    	    <li>{{ $error }}</li>
						    	@endforeach
						    </ul></div>
						@endif

						<div class="form-group">
							<label for="name" class="col-md-3 control-label">Name of Teacher</label>
							<div class="col-md-6">
								<input id="name" type="text" class="form-control" name="name" value="{{ $teacher->name }}" autofocus>
							</div>
						</div>

						<div class="form-group">
							<label for="class" class="col-md-3 control-label">Class</label>
							<div class="col-md-6">
								<select id="class" class="form-control" name="class_id">
									<option value=""> -- Choose Class -- </option>
									@foreach($classroom as $classroom)
									    <option value="{{ $classroom->class_id }}" {{ $classroom->class_id == $teacher->class_id ? 'selected' : '' }}>{{ $classroom->name }}</option>
									@endforeach
								</select>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-3 col-md-offset-3">
								<button type="submit" class="btn btn-primary">Save</button>
								<a href="{{ url('teacher') }}" class="btn btn-warning">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/teacher/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>List of Teacher
						<a href="{{ route('teacher.create') }}" class="btn btn-success pull-right">Insert</a><br></h4>
				</div>

				<div class="panel-body">
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>Teacher name</th>
								<th>Action</th>
							</tr>
						</thead>

						<tbody>
							@foreach ($teacher as $teacher)
							<tr>
								<td>{{ $teacher->teacher_id }}</td>
								<td>{{ $teacher->name }}</td>
								<td>
									<form method="POST" action="{{ route('teacher.destroy', $teacher->teacher_id) }}">
										{{ csrf_field() }}
										{{ method_field('DELETE') }}
										<a href="{{ route('teacher.edit', $teacher->teacher_id) }}" class="btn btn-primary">Edit</a>
										<button type="submit" class="btn btn-danger">Delete</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection